name: Sync with Upstream

on:
  schedule:
    - cron: '30 04 * * *'  # 每天午夜自动同步
  workflow_dispatch:  # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name "xiaohuolu"
          git config --global user.email "wp_uav@163.com"

      - name: Add Upstream and Fetch
        run: |
          git remote add upstream ${{ secrets.UPSTREAM_REPO }}
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
